### PR TITLE
Change 6LoWPAN test configs.

### PR DESCRIPTION
**Pull request by SeppoTakalo**
* Channel to 17
* Use PANID filter

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
Reopened from feature branch.

**Comment by JanneKiiskila** [comment]
This test run should then pass, if the lab is now matching this config.

**Comment by JanneKiiskila** [comment]
@teetak01 - I think we have to update our mbed-os-example-build scripts in ci-scripts repo as well to match this, we're not having now the same channel (which we shouldn't call mesh channel, but it's either 6lowpan or thread channel, there is no such thing as mesh channel).

**Comment by SeppoTakalo** [comment]
What is the reason for -client-executor failing? I don't understand it. Looks like its not even using this PR, it fetches the binaries from elsewhere.

**Comment by JanneKiiskila** [comment]
:53:45 08:53:45.927 | D1 <<< DutThread: Starting mbed Client example in IPv6 mode
10:53:45 08:53:45.927 | D1 <<< DutThread: [EasyConnect] Using Mesh
10:53:45 08:53:45.927 | D1 <<< DutThread: [EasyConnect] Connecting to Mesh..
10:53:46 08:53:46.841 | MRC     Thread-2: socketio resource_reset_response event
 -> mesh networking failing, we didn't update the client-ci-test script quickly enough.

**Comment by JanneKiiskila** [comment]
But, it's in - let's test it... Any dummy change should do, the ci script change was also merged in.

**Pull request merged**
