### PR TITLE
Add Realtek RTL8195AM to docs

### PR DESCRIPTION
**Pull request by MarceloSalazar**
## Status
**HOLD**

## Migrations
NO

## Description
Add instructions and configuration to get the Realtek platform supported in the Mbed OS Example Client app.

### CODE REVIEW

**Comment by MarceloSalazar** [comment]
@JanneKiiskila @samchuarm please review and share your thoughts

**Comment by teetak01** [comment]
Or just rebase this branch. It really depends is there plans to merge this to master at some point?

**Comment by MarceloSalazar** [comment]
I picked the json config from master and added docs, so should be ok.
Let me know if you see any problem.

**Comment by JanneKiiskila** [comment]
Well, it's 3 separate git commits of which  one's description is "ADd". Git rebase squash to clean the history at least?

**Comment by MarceloSalazar** [comment]
My bad - typing in the browser doesn't help - hope is now ok.

**Comment by MarceloSalazar** [comment]
Pending discussion on whether we'll support this platform due to problems with Online IDE.
@samchuarm

**Comment by JanneKiiskila** [comment]
Can we close this one?

**Comment by MarceloSalazar** [comment]
Can we please put this on hold until this PR (https://github.com/ARMmbed/mbed-os/pull/5719) is merged and released in an upcoming version of Mbed OS?

**Comment by JanneKiiskila** [comment]
I don't see the point - the OOB branch needs to be merged in NOW. This one is NOT in that branch, but most of the changes here - are already in the master? It's too late to hold back now.

**Comment by MarceloSalazar** [comment]
no problem, I'll retarget this PR to master

**Pull request closed without merging**
