### PR TITLE
Add Nucleo F429ZI  to known issues list

### PR DESCRIPTION
**Pull request by JanneKiiskila**
It's not linking with IAR.

### CODE REVIEW

**Comment by MarceloSalazar** [comment]
@ashok-rao please review this

**Comment by JanneKiiskila** [comment]
Actually, it's not specific to those boards either - I think it's ALL boards with IAR.

**Comment by JanneKiiskila** [comment]
@ashok-rao , please check again... ;)

**Comment by ashok-rao** [comment]
I don't think so @JanneKiiskila , the Client example (with ethernet) passed clearly with NUCLEO_F746ZG using IAR (v7.70)..so maybe it's only a few targets & that too only with Nanostack included?? Maybe?? what do you think?

**Comment by JanneKiiskila** [comment]
Undoing my last commit, force push and some git rebase -i / squash action to make the commit list shorter.

**Pull request merged**
