### PR TITLE
Network handling to net_client.cpp & clean simpleclient.h

### PR DESCRIPTION
**Pull request by JanneKiiskila**
Attempt to simplify main.cpp:
-   Clean up main.cpp from network related issued - to new files.
-   Cleanup simpleclient.h so that it is a clean header file
    and implementation is in simpleclient.cpp.
- Return with 0 in main.ccp if no network address given.

### CODE REVIEW

**Comment by jankii01** [comment]
How about this? Anyways, please note it doesn't work yet. Registration does not happen and for the love of god I can't figure out why not. I don't think I touched that part but...

**Comment by MarceloSalazar** [comment]
Thanks @jankii01 , I like the idea of simplifying the example. However, I see lots of code is being moved to client_net.cpp but we may need to consider simplifying it and even main.cpp quite a bit more. @sg- may want to have a look.

Also, I'd like @janjongboom to review and comment on this.
AFAIK he's been delivering successful workshops with a [simple-client API](https://developer.mbed.org/teams/sandbox/code/simple-mbed-client/file/680c2a46cc8a/simple-mbed-client.h) and things could be reused.
Here is an example of a simple [main.cpp](https://developer.mbed.org/teams/sandbox/code/simple-mbed-client-example/file/70eaf98b5486/source/main.cpp) 

Thoughts?

**Comment by jankii01** [comment]
@MarceloSalazar, seems @janjongboom has done an "easyconnect.h" which then pretty much almost the same #ifdef jungle we have here (I didn't know about that example, we could have possibly re-used it). So, we have now ~2 similar implementations for that part - it still not much simpler in reality.

**Comment by jankii01** [comment]
Seems though easyconnect.h doesn't have any support for UBLOX ODIN WiFi.

**Comment by janjongboom** [comment]
@jankii01 @MarceloSalazar Yeah I see the same #ifdef jungle in every example project, so I threw it together in easyconnect... If it's useful for mbed-os-example-client we might just switch over to that.

**Comment by jankii01** [comment]
@janjongboom , @MarceloSalazar, @teetak01, @anttiylitokola @TeroJaasko  - it would actually make sense to have ONE connectivity component we use. We have the exact same need also in mbed-cloud-client-example as well, so we could re-use it there. However, I find it rather dubious to have actual implementation in an .h-file, so if we were to go that route - could we have a clean .h-definition and the actual implementation in a real .cpp-file?

**Comment by janjongboom** [comment]
@jankii01 For easyconnect we can just link the library (.lib file)...

In general though I like to have simple header-only libraries for small stuff. They're easy to deal with.

**Comment by jankii01** [comment]
rebuild

**Comment by yogpan01** [comment]
@MarceloSalazar @janjongboom This brings me to question, why is this easy-connect not part of mbed-os API offering ? The whole idea of having mbed-os network APIs was to consolidate all different network bearers under one hood but seems that developers have to write own "ifdef jungle" API  to sort this basic issue which frankly should be OS's responsibility.
@sg- Would you consider taking this Easy Connect API to be under mbed-os ?

**Comment by janjongboom** [comment]
@yogpan01 @sg- I think the main reason would be that easy-connect requires external libraries which are not part of mbed OS 5. **But** I do believe we should use easy-connect for all our own demo's. I wrote it because I got tired of this #ifdef hell...

**Comment by JanneKiiskila** [comment]
Rebased this on top of latest master, review comments would be greatly appreciated. @MarceloSalazar @yogpan01 @TeroJaasko

**Comment by janjongboom** [comment]
My points are still kinda the same as last time:

1. The code in client_net is so generic, and should be used in all of our mbed Cloud / mbed Device Connector examples that it should belong in a separate library. EasyConnect is the obvious choice.
2. For a PR that aims to simplify this example, these diff numbers are worrying: +521 −288.
3. I applaud simplifying main.cpp, but it still clocks in at 433(!) lines of code. So we have ~600 lines of code to bootstrap stuff (simpleclient and client_net) and we still need >400 lines of code to get our cloud service working. This is ridiculous (not aimed at you personally).

Some other notes:

1. I like `mbed_trace_init` but maybe put it behind a flag in mbed_app.
2. Why `NetworkInterface**` and not `NetworkInterface*`.

**Comment by JanneKiiskila** [comment]
Fully agree with @yogpan01 here - we really should not leave this #ifdef hell to the developers - we should really get the easy-connect to be part of mbed OS itself.

**Comment by JanneKiiskila** [comment]
But, it also then means that if we are to start using easy-connect, then the .lib references in that example MUST be maintained (and tested). Right now at least the atmel RF driver is behind.

**Comment by JanneKiiskila** [comment]
@janjongboom  - well, we have this now as well.
https://github.com/ARMmbed/mbed-os-example-client/pull/176

@MarceloSalazar @sg- for this to really fly, mbeOS team needs to take ownership of the easyconnect - setup CI & testing for it. We will just be one consumer for it then and you deal with the network ugliness.

**Comment by JanneKiiskila** [comment]
Closing this out, easy-connect it is.

**Pull request closed without merging**
