### PR TITLE
Support for STM Radio Expansion Boards

### PR DESCRIPTION
**Pull request by betzw**
## Status
**PROPOSAL**

## Migrations
NO

## Related PRs
#323

### CODE REVIEW

**Comment by teetak01** [comment]
@betzw this PR might simplify this https://github.com/ARMmbed/wifi-x-nucleo-idw01m1/pull/6

Having even more .mbedignore files makes the UX pretty bad.

**Comment by betzw** [comment]
Could you pls. synchronize on this within ARM and especially with @JanneKiiskila.
As far as I understand the trade-off is between smaller/correcter builds versus user experience. 
I personally would prefer smaller builds - i.e. the old school approach where the developer should understand what he is doing - but not everybody might agree on this :disappointed:

**Comment by betzw** [comment]
Btw, it might be worthwhile to first merge [PR \#52](https://github.com/ARMmbed/easy-connect/pull/52), adapt the link to `easy-connect` in this PR and merge it only then.

**Comment by betzw** [comment]
Ok I have updated `easy-connect.lib`!
@teetak01, @JanneKiiskila, it would be great if we could merge this PR asap. Pls. let me know.

**Comment by JanneKiiskila** [comment]
Needs re-basing, tests are now failing on the README.md conflict.

**Comment by betzw** [comment]
The `network-interface` as described in `README.md` just talks about `WIFI` rather than `WIFI_ESP8266`, `WIFI_ODIN` ecc. as expected by `easy-connect`.
Is this intentianl?

**Comment by JanneKiiskila** [comment]
That's not right, should be fixed.

**Comment by betzw** [comment]
Re-base done (and `README.md` corrected with respect to `network-interface` & `WIFI`).

**Comment by teetak01** [comment]
@JammuKekkonen please check & merge if you are happy with this.

**Comment by betzw** [comment]
bump @JanneKiiskila, @JammuKekkonen, @teetak01

**Comment by betzw** [comment]
bump @screamerbg

**Comment by betzw** [comment]
@SeppoTakalo, not sure why this is stuck since a week now?

**Comment by teetak01** [comment]
Verified via seperate test-PR #336

**Pull request merged**
