### PR TITLE
Moved the problem chapter under Building.

### PR DESCRIPTION
**Pull request by peknis01**
Any better? Just let me know if we need more reorganizing.

### CODE REVIEW

**Comment by yogpan01** [comment]
@bridadan Is this fine now ?

**Comment by peknis01** [comment]
Yogesh, your call. I think you could do some initial stuff here and I'll check then how it looks.

**Comment by bridadan** [comment]
I realize this might be a lot of changes to get in before the release, but I thought I'd bring it up. The changes here definitely look good, but I think we can still improve the instructions for new people coming into mbed.

**Comment by yogpan01** [comment]
@bridadan I will merge this PR now and we will follow-up on your proposal in a separate PR.
@peknis01 FYI

**Pull request merged**
