### PR TITLE
Newer Atmel RF driver

### PR DESCRIPTION
**Pull request by JanneKiiskila**
12 commits up ahead in the master branch.

### CODE REVIEW

**Comment by jankii01** [comment]
Strange, it failed on the WiFi test - this change has nothing to do with WiFi.

**Comment by JanneKiiskila** [comment]
@kimlep01 , any chance of getting some tests done with the latest?

**Comment by kimlep01** [comment]
Ok I will run our tests today with this PR.

**Comment by kimlep01** [comment]
Looks good from our point of view

**Comment by JanneKiiskila** [comment]
The commit message lists the changes inbetween, I didn't spot any removal of AT86RF231?

**Comment by JanneKiiskila** [comment]
Newer (57f2276) Atmel RF driver
12 commits up ahead in the master branch, short log below

57f2276 Kevin Bracey - Merge pull request #50 from ARMmbed/echo_fix
d314a4c Kevin Bracey - Stop using deprecated mbed API
3fe3383 Kevin Bracey - Disable power saving
aeaf4cc Kevin Bracey - Attempt to tighten CCA logic
059ca03 Kevin Bracey - Tidy register bit manipulation
2d00da1 Kevin Bracey - Avoid pointless floating-point
0ae1c32 Kevin Bracey - Don't load frame buffer until CCA start
c950aae Kevin Bracey - Move lock on transmit API
51a3857 Kevin Bracey - Avoid sending multiple TX_DONE callbacks
10b0300 Kevin Bracey - Correct transmit callback retries reports
fb6360d Kevin Bracey - Feed randomness into randLIB directly

**Comment by JanneKiiskila** [comment]
Wi-Fi test not executed (not in use now) but this does not have any impact on WiFi.

**Pull request merged**
