### PR TITLE
Updating ISM43362 WIFI driver for STM32 DISCO boards

### PR DESCRIPTION
**Pull request by jeromecoutant**
## Status
**READY**

## Description

Here is update for ISM43362 wifi driver

## Related PRs

https://github.com/ARMmbed/easy-connect/pull/98

### CODE REVIEW

**Comment by jeromecoutant** [comment]
@SeppoTakalo @adustm @LMESTM @bcostm

**Comment by SeppoTakalo** [comment]
This application is considered obsoleted by Mbed Cloud Client examples, so I'm unsure whether someone will merge these in.

**Comment by SeppoTakalo** [comment]
CC: @JanneKiiskila

**Comment by teetak01** [comment]
I think the easy-connect PR should be merged in first, and then updated to this PR?

We can take some PRs in here still for a while, but if something breaks, it probably will go unfixed.

**Comment by bcostm** [comment]
The new example is here https://github.com/ARMmbed/mbed-cloud-client-example

**Comment by jeromecoutant** [comment]
@teetak01e asy-connect PR is now merged

Rebase is done

Thx

**Comment by jeromecoutant** [comment]
@teetak01 easy-connect PR is now merged

Rebase is done

Thx

**Pull request merged**
