### PR TITLE
OOB test mbed OS 5.4

### PR DESCRIPTION
**Pull request by JanneKiiskila**
PR to test things.

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
Some funny business with the Jenkinsfile, it seems to checkout wrong mbed-client lib?

**Comment by JanneKiiskila** [comment]
rebuild

**Comment by JanneKiiskila** [comment]
Rebased a bit, left out one unnecessary commit (temporary mbed-client.lib update). Force pushed, so it will re-write the history a bit (apologies for that).

**Comment by JanneKiiskila** [comment]
rebuild

**Comment by yogpan01** [comment]
rebuild

**Comment by yogpan01** [comment]
Merging this PR, IAR for ODIN is failing the PR check but this is a Known issue listed here #203

**Pull request merged**
