### PR TITLE
Bring in performance improvements for atmel driver

### PR DESCRIPTION
**Pull request by teetak01**
Atmel driver update improves multi-node performance and decreases packet loss

### CODE REVIEW

**Comment by teetak01** [comment]
Seemed to have dependency to Mbed OS 5.6.4

**Comment by teetak01** [comment]
@artokin @tommikas is the Jenkinsfile using some older version of Mbed OS?

**Comment by tommikas** [comment]
Seems to be using the latest tag: 
https://github.com/ARMmbed/mbed-os-example-client/blob/master/Jenkinsfile#L5-L15

**Comment by teetak01** [comment]
Well, then it should pass soon enough. The driver-update requires at least Mbed OS 5.6.4

**Comment by JanneKiiskila** [comment]
Which is already available. :-)

**Comment by teetak01** [comment]
Closing this, there is fixes to ST-WIFI driver and that will come in via another PR.

**Pull request closed without merging**
