### PR TITLE
Thread config update. This is only because of jenkins.

### PR DESCRIPTION
**Pull request by karsev**
New Thread network configurations. Dependency to the mesh-api changes -> https://github.com/ARMmbed/mbed-os/pull/3736
And the gateway -> https://github.com/ARMmbed/nanomesh-applications/pull/390
And the Thread BR -> https://github.com/ARMmbed/k64f-border-router-private

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
rebuild

**Comment by teetak01** [comment]
In my opinion this PR should be rejected. CI-requirements should be done on CI, not hardcoding the values to example application.

**Comment by JanneKiiskila** [comment]
Don't we need to modify the mbed_app.json as well to match this, ifi we change the binaries? @artokin

**Comment by karsev** [comment]
same change in 110.

**Pull request closed without merging**
