### PR TITLE
Updating mbed-os to mbed-os-5.7.7

### PR DESCRIPTION
**Pull request by cmonr**
Please test this PR

If successful then merge, otherwise provide a known issue.
Once you get notification of the release being made public then tag Master with mbed-os-5.7.7 .

### CODE REVIEW

**Comment by teetak01** [comment]
rebuild

**Comment by JanneKiiskila** [comment]
U-blox failing the CI-tests due to known issue - https://github.com/ARMmbed/mbed-os/issues/6003

**Comment by cmonr** [comment]
@jannehekkala Is there a new issue other than 6003? It looks like that one is already marked as closed.

**Comment by teetak01** [comment]
@cmonr Fix version Mbed Os 5.8

**Pull request closed without merging**
