### PR TITLE
Add example how to use big payload in application side.

### PR DESCRIPTION
**Pull request by anttiylitokola**
Change status ticker color to green.
Use delayed response for blink execution.

### CODE REVIEW

**Comment by anttiylitokola** [comment]
@yogpan01

**Comment by anttiylitokola** [comment]
Compilation will not work until mbed-client and mbed-client-c changes are pushed to mbed-os.

**Comment by yogpan01** [comment]
@anttiylitokola https://github.com/ARMmbed/mbed-os/pull/2632 should be merged first then we can merge this one.

**Comment by yogpan01** [comment]
rebuild

**Comment by anttiylitokola** [comment]
rebuild

**Comment by yogpan01** [comment]
Can be closed as this PR is already merged through OOB testing repo changes.

**Pull request closed without merging**
