### PR TITLE
Set trace level to `info`

### PR DESCRIPTION
**Pull request by betzw**
## Description
@SeppoTakalo should improve situation for issue ARMmbed/mbed-os-example-client#247.

### CODE REVIEW

**Comment by betzw** [comment]
Can someone pls. let me know why several of the checks are failing (seems as if I have no access to the `Details`)?

**Comment by SeppoTakalo** [comment]
Due the security reasons, some of our CI jobs don't execute tests from pull requests coming outside of these repositories. Therefore they fail.

Somebody from Client team should review this and replicate the PR into a local branch. @yogpan01 @teetak01 can you help on this?

**Comment by teetak01** [comment]
Well, it the PR itself if fine, but is this really the right way to "fix" this? There seems to an issue that the mesh cannot handle the activity. This is only hiding it.

**Comment by betzw** [comment]
Don't think that there is a way to fix this [issue](https://github.com/ARMmbed/mbed-os-example-client/issues/247) as it basically is a timing issue which it caused by the huge amount of debug messages when using trace level `debug`. 
On the other hand, setting the trace level to `info` would allow users to be able to see what's going on in the stack while still having working connections.

**Comment by teetak01** [comment]
Could same kind of delays be caused if the application is doing some heavy processing (like TLS operations) or some heavy customer application decoding?

**Comment by betzw** [comment]
In theory yes, but it must be very heavy processing ... I mean producing debug output over printf and the like is so time consuming because it typically is implemented in polling mode, i.e. busy waiting for each character to be sent over the serial line, inhibiting any other kind of processing to proceed.

**Comment by JanneKiiskila** [comment]
Is there a conclusion on this? @yogpan01 @SeppoTakalo

**Comment by betzw** [comment]
As far as I know, not really.
What I can add is that this would have been very helpful while we worked on #266.

**Comment by teetak01** [comment]
Part of https://github.com/ARMmbed/mbed-os-example-client/pull/327 already.

**Pull request closed without merging**
