### PR TITLE
Fix example of mbed_app.json for non-K64F boards

### PR DESCRIPTION
**Pull request by toyowata**
See #84 for detail

### CODE REVIEW

**Comment by yogpan01** [comment]
-1 for this PR, till we get official answer from @bogdanm 
The original implementation has been tested with mbed-os-5.1.0 release and now with latest mbed-os release this seems to be broken, so what is the right way ?

The latest mbed-os and mbed-cli seems to have different behaviour with config json parameters, this needs to be moved to mbed-os team to verify and propose what has changed. Client can only change documentation when its sure how the mbed Configuration mechanism is working.
@bogdanm @0xc0170 @c1728p9 Please check this and propose what is the correct way to pass these parameters?

**Comment by bogdanm** [comment]
I'm not sure I understand the issue completely. If I got this right, you're trying to provide different per-board configuration, based on the board's ability to provide an entropy source. The proper way to do this is to provide a configuration parameter for this (not a macro) and override it based on the target, in the same way you do (for example) for `wifi-tx` and `wif-rx`. Ideally, this configuration shouldn't come from `mbed-os-example-client`, since `mbed-os-example-client` shouldn't have to track which targets have entropy implementations and which don't; ideally, this information would come from the target itself. But for a quick fix, defining this parameter in `mbed-os-example-client` would work too. Generally speaking, when you have to define some configuration that changes based on the compilation target, consider defining it as a configuration parameter instead of a macro. One of the main advantages of configuration parameters is that they can easily be overriden based on the target.

Another observation is that regardless of the above paragraph, the documentation change in this PR doesn't look right, since it looses the definition of `MBEDTLS_USER_CONFIG_FILE`.

**Comment by XtrmDesignsllc** [comment]
This is a pull request to add functionality to GR-PEACH Renesas Cortex A9 RZ_A1H platform. This platform has a reset and a user button.
--------------------------------------------------------------------------------------------------------

1.	If your platform has a button this can be used instead of the fake counter
2.	Needs an additional button or if only 1 you can let the counter run and then just unregister
3.	mbed TLS needs a TRNG driver and later we’ll be providing a non-volatile seed implementation that needs access to a storage driver (coming soon in the hal) for EEPROM or FLASH

Please make a pull request against the example if you have the time and the board supports these features.

SG

From: Peter Ateshian <peter.ateshian@renesas.com>
Date: Wednesday, September 14, 2016 at 10:08 AM

A question for your organization – please :
 
 
On Topic of a Full GR-PEACH ARM Mbed5.1.2 platform port:
We mapped the FRDM K64F ARM mbed-os-client  web to Our current RZ_A1H demo and it has has several limitations:

1. NO direct user platform interaction as Simulated button push (K64F has real 2nd button counter)
2. No unregister function  (K64F has Unregister option)
3. NULL Entropy security work around

**Comment by toyowata** [comment]
Closed, because it now points to the TLS Porting guide.

**Pull request closed without merging**
