### PR TITLE
Change socket mode to UDP for mesh in Jenkinsfile

### PR DESCRIPTION
**Pull request by kimlep01**
Change socket mode to UDP for mesh in Jenkinsfile

* Change binding mode to UDP in simpleclient.h if building for mesh
This is a workaround for IOTCLT-1296

@teetak01 @SeppoTakalo 
CC @jankii01 @artokin

### CODE REVIEW

**Comment by jankii01** [comment]
We could also consider modifying the .h-file to have this part;

#if MBED_CONF_APP_NETWORK_INTERFACE == MESH_LOWPAN_ND
    NETWORK_STACK = M2MInterface::Nanostack_IPv6;
#elif MBED_CONF_APP_NETWORK_INTERFACE == MESH_THREAD
    NETWORK_STACK = M2MInterface::Nanostack_IPv6;
#endif

applied also to the TCP vs UDP mode setting. Might be useful for others, too.

**Comment by SeppoTakalo** [comment]
Yes!
That would be better solution.

**Comment by jankii01** [comment]
//Select binding mode: UDP or TCP -- note - Mesh networking is IPv6 UDP ONLY
#if MBED_CONF_APP_NETWORK_INTERFACE == MESH_LOWPAN_ND || MBED_CONF_APP_NETWORK_INTERFACE == MESH_THREAD
	M2MInterface::BindingMode SOCKET_MODE = M2MInterface::UCP;
	M2MInterface::NetworkStack NETWORK_STACK = M2MInterface::LwIP_IPv6;
#else
	// WiFi or Ethernet supports both - TCP by default to avoid
	// NAT problems, but UDP will also work - IF you configure
	// your network right.
    M2MInterface::BindingMode SOCKET_MODE = M2MInterface::TCP;
    // Select network stack mode: IPv4 or IPv6 - Eth + Wifi can be either
    // Remember to match the mbed_app.json with this choice
    M2MInterface::NetworkStack NETWORK_STACK = M2MInterface::LwIP_IPv4;
#endif


I think we should resolve the IPv4/IPv6 issue as well...

**Comment by jankii01** [comment]
I think this should resolve it: https://github.com/ARMmbed/mbed-os-example-client/pull/139/files

**Comment by jankii01** [comment]
@SeppoTakalo  @kimlep01  Ideally we could also handle the UDP vs. TCP via the mbed_app.json file, I don't think it's ideal one has to tweak the source files for configuration issues but I haven't figured out yet a way to do that.

**Comment by jankii01** [comment]
Please see also this; https://github.com/ARMmbed/mbed-os-example-client/issues/137

**Comment by kimlep01** [comment]
@jankii01 I just ran tests with latest binaries from master as #139 was merged and 6lowpan has SOCKET_MODE : TCP enabled again.

**Pull request closed without merging**
