### PR TITLE
Added a boolean to disable blinky ticker when a blink pattern is posted

### PR DESCRIPTION
**Pull request by sarahmarshy**
The blink pattern was not being updated properly with Post requests because of the status ticker. I have added a boolean to disable the ticker from updating the LED when a blink pattern is executing.

### CODE REVIEW

**Comment by sarahmarshy** [comment]
@mikaleppanen Is there an issue for the CI of this repo?

**Comment by yogpan01** [comment]
rebuild

**Comment by sarahmarshy** [comment]
@yogpan01, I've just reviewed the build failure. I cannot get this to compile with IAR on master, either. Can you?

**Comment by yogpan01** [comment]
rebuild

**Comment by teetak01** [comment]
rebuild

**Comment by teetak01** [comment]
ok fixed now, there was a minor Linux != Windows script incompatibility issue...

**Comment by yogpan01** [comment]
@sarahmarshy can you please rebase your PR ? The IAR CI build job is now fixed.

**Comment by anttiylitokola** [comment]
These changes are covered in https://github.com/ARMmbed/mbed-os-example-client/pull/79, hence closing this one

**Pull request closed without merging**
