### PR TITLE
[STM] Add wifi ism43362 for DISCO_L475_IOT01A

### PR DESCRIPTION
**Pull request by adustm**
## Description
DISCO_L475VG_IOT01A and DISCO_F413ZH have an Inventek wifi module. This PR allows the DISCO_L475VG_IOT01A  to connect to the Device connector.

### CODE REVIEW

**Comment by teetak01** [comment]
Cleanup + rebase.

**Comment by adustm** [comment]
Hello @teetak01,

I've rebased the example
I've removed the mbedignore file + updated the Readme file accordingly.

Kind regards
Armelle

**Comment by adustm** [comment]
Hello @JanneKiiskila 
Thank you for merging the PR.
Do you know when the easy connect library will be updated in this repository ?

**Comment by JanneKiiskila** [comment]
Oh, that should have been included with this PR. I'll do a pull for that ASAP.

**Comment by adustm** [comment]
Ok, I was not aware of the release process for easy-connect.
Thank you

**Comment by JanneKiiskila** [comment]
https://github.com/ARMmbed/mbed-os-example-client/pull/385 is in now.

**Comment by adustm** [comment]
Thank you so much!

**Pull request merged**
