### PR TITLE
Change 6LoWPAN test configs.

### PR DESCRIPTION
**Pull request by SeppoTakalo**
* Channel to 17
* Use PANID filter

@yogpan01 @JanneKiiskila Please review&accept. This is now the configuration for 6LoWPAN test network.

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
Looks good to me, but there's a lot of tests now failing, wonder why...

**Comment by JanneKiiskila** [comment]
"+ git checkout 41d76b0fcb13316857778b07ca8e2918b311fa53
fatal: reference is not a tree: 41d76b0fcb13316857778b07ca8e2918b311fa53
Build step 'Execute shell' marked build as failure"

-- fork issue again... ;/

**Comment by JanneKiiskila** [comment]
I added Seppo you write rights now, you could store that patch from your fork to a file and then make a branch from the real mbed-os-example-client repo and do git am there and then push that branch to Github to get the real PR checks working. Has the lab side changes been done already?

**Comment by SeppoTakalo** [comment]
I only touched the `Jenkinsfile` and pipeline build is now passing. Do you want me to resubmit this from a feature branch?

Lab changes were done yesterday. All 6LP HW tests should now fail, until this is merged in.

**Pull request closed without merging**
