### PR TITLE
Updating mbed-os to mbed-os-5.4.2

### PR DESCRIPTION
**Pull request by 0xc0170**

### CODE REVIEW

**Comment by teetak01** [comment]
Seems to have some issues on IAR with non-K64F boards:

```
16:20:02 [NUCLEO_F429ZI IAR thd ATMEL] Link: mbed-os-example-client
16:20:01 [NUCLEO_F429ZI IAR thd MCR20] Failed in branch NUCLEO_F429ZI IAR thd MCR20
16:20:02 [NUCLEO_F429ZI IAR thd ATMEL] Error[Lp011]: section placement failed
16:20:02 [NUCLEO_F429ZI IAR thd ATMEL]             unable to allocate space for sections/blocks with a total estimated
16:20:02 [NUCLEO_F429ZI IAR thd ATMEL]                       minimum size of 0x3081c bytes (max align 0x8) in
16:20:02 [NUCLEO_F429ZI IAR thd ATMEL]                       <[0x200001b0-0x2002ffff]> (total uncommitted space
16:20:02 [NUCLEO_F429ZI IAR thd ATMEL]                       0x2fe50).
```

**Comment by yogpan01** [comment]
@teetak01 @0xc0170 Isnt this a known issue https://github.com/ARMmbed/mbed-os-example-client/issues/194 ?

**Comment by teetak01** [comment]
Nope, this is a build-fail on multiple boards with IAR.

**Comment by 0xc0170** [comment]
>Nope, this is a linking-fail on multiple boards with IAR.

sectons placements again - aka heap size?  IF yes, this should get our attention : https://github.com/ARMmbed/mbed-os/issues/4067

**Comment by yogpan01** [comment]
https://github.com/ARMmbed/mbed-os-example-client#known-issues @0xc0170 Is this still issue ?

**Comment by yogpan01** [comment]
Not valid anymore. there is mbed OS 5.4.3 release available now

**Pull request closed without merging**
