### PR TITLE
Doc update thr

### PR DESCRIPTION
**Pull request by karsev**
Described where to find settings
the channel setting section removed
Related to https://github.com/ARMmbed/mbed-os-example-client/issues/211

### CODE REVIEW

**Comment by karsev** [comment]
@artokin @JanneKiiskila

**Comment by betzw** [comment]
I personally wouldn't remove the "Channel settings" chapter completely as I wouldn't know in which other place/doc one could find the information about `*-channel` and `*-channel-page`!?!

**Comment by karsev** [comment]
The channel chapter didn't provide much information about channel setting itself. In this branch the mbed-mesh-api is referenced in the beginning where you can find information about all settings.

**Comment by betzw** [comment]
Do you mean [mbed-mesh-api](https://github.com/ARMmbed/mbed-os/tree/master/features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed_lib.json)?
If yes, well, I would say that this reference lacks at least the information with respect to 2.4GHz vs. sub-GHz shields.

**Comment by karsev** [comment]
I put the channel chapter back for clarification.

**Comment by JanneKiiskila** [comment]
@karsev  @artokin 
Are we done with these now, so that I can merge it in?

**Comment by JanneKiiskila** [comment]
Merged against the re-structuring done by Yogesh... @karsev - you should check it's still OK. Structure was changed quite a lot.

**Comment by karsev** [comment]
It is ok.

**Pull request merged**
